import { Service, Staff, Product, Booking, Order, Invoice, Submission } from '../types';

export const MOCK_SERVICES: Service[] = [
  {
    id: 's1',
    client_id: 'placeholder-tenant-id',
    name: 'Classic Haircut',
    description: 'Precision scissor and clipper cut, finished with a warm lather neck shave and styled with premium pomade.',
    duration_minutes: 30,
    price: 35,
    category: 'Haircuts',
    active: true,
  },
  {
    id: 's2',
    client_id: 'placeholder-tenant-id',
    name: 'The Executive Cut & Style',
    description: 'Detailed consultation, hair wash, scalp massage, custom cut, blow dry style, and personal product recommendation.',
    duration_minutes: 45,
    price: 50,
    category: 'Haircuts',
    active: true,
  },
  {
    id: 's3',
    client_id: 'placeholder-tenant-id',
    name: 'Buzz Cut & Fade',
    description: 'Single-guard all-over cut, or skin fade utilizing foils for an ultra-clean, high-contrast look.',
    duration_minutes: 25,
    price: 28,
    category: 'Haircuts',
    active: true,
  },
  {
    id: 's4',
    client_id: 'placeholder-tenant-id',
    name: 'Classic Hot Towel Shave',
    description: 'Traditional straight razor shave with pre-shave oil, protective hot towel wrap, warm lather, and cooling aftershave balm.',
    duration_minutes: 45,
    price: 45,
    category: 'Shaves',
    active: true,
  },
  {
    id: 's5',
    client_id: 'placeholder-tenant-id',
    name: 'Beard Grooming & Lineup',
    description: 'Beard trim, shaping, razor line-up on the cheeks, finished with nourishing sandalwood beard oil.',
    duration_minutes: 30,
    price: 30,
    category: 'Shaves',
    active: true,
  },
  {
    id: 's6',
    client_id: 'placeholder-tenant-id',
    name: 'Scalp Treatment & Clarifying Wash',
    description: 'Tea tree oil scalp treatment, deep clarifying wash, and conditioning treatment to stimulate healthy hair growth.',
    duration_minutes: 20,
    price: 25,
    category: 'Treatments',
    active: true,
  },
  {
    id: 's7',
    client_id: 'placeholder-tenant-id',
    name: 'Charcoal Face Mask & Peel',
    description: 'Pore-cleansing activated charcoal mask, warm steaming towels, facial massage, and moisturization.',
    duration_minutes: 30,
    price: 35,
    category: 'Treatments',
    active: true,
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: 'b1',
    client_id: 'placeholder-tenant-id',
    name: 'Marcus Vance',
    bio: 'Founder and Master Barber with over 15 years of experience. Marcus specializes in classic gentleman cuts, straight-razor shaving, and meticulous beard styling.',
    photo_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'b2',
    client_id: 'placeholder-tenant-id',
    name: 'Sofia Reyes',
    bio: 'Sofia is an expert in modern hair trends, texturized crops, and clean skin fades. She brings creative precision and a fresh aesthetic to every client.',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'b3',
    client_id: 'placeholder-tenant-id',
    name: 'Dorian Hayes',
    bio: 'Specializing in detailed beard shaping, razor lining, and structural grooming. Dorian’s steady hands make his hot towel straight-razor shave an unforgettable ritual.',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    active: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    client_id: 'placeholder-tenant-id',
    name: 'Sandalwood Matte Pomade',
    description: 'Strong hold pomade with a natural matte finish. Perfect for textured, structured, or side-parted styles. Water-soluble and washes out easily.',
    price: 24,
    photo_url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&auto=format&fit=crop&q=80',
    stock_qty: 12,
    is_hidden: false,
  },
  {
    id: 'p2',
    client_id: 'placeholder-tenant-id',
    name: 'Hydrating Beard Oil & Balm Set',
    description: 'Infused with jojoba oil, argan oil, and a subtle cedarwood fragrance. Conditions beard hair, eliminates itch, and leaves a premium satin shine.',
    price: 32,
    photo_url: 'https://images.unsplash.com/photo-1626015276510-97a53600b285?w=500&auto=format&fit=crop&q=80',
    stock_qty: 8,
    is_hidden: false,
  },
  {
    id: 'p3',
    client_id: 'placeholder-tenant-id',
    name: 'Classic Sandalwood Aftershave Tonic',
    description: 'Traditional cooling tonic that soothes freshly shaved skin, closes open pores, and reduces razor irritation with deep antiseptic properties.',
    price: 18,
    photo_url: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=500&auto=format&fit=crop&q=80',
    stock_qty: 0, // out of stock
    is_hidden: false,
  },
  {
    id: 'p4',
    client_id: 'placeholder-tenant-id',
    name: 'Professional Styling Clay',
    description: 'Medium hold clay with high density bentonite clay to add natural volume and thickness to finer hair types. Zero shine, highly flexible.',
    price: 22,
    photo_url: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=500&auto=format&fit=crop&q=80',
    stock_qty: 15,
    is_hidden: false,
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bkg1',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Arthur Pendragon',
    customer_email: 'arthur@camelot.org',
    customer_phone: '555-123-4567',
    service_id: 's1',
    staff_id: 'b1',
    start_time: '2026-07-21T09:30:00.000Z',
    status: 'confirmed',
  },
  {
    id: 'bkg2',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Elena Rostova',
    customer_email: 'elena@rostov.io',
    customer_phone: '555-987-6543',
    service_id: 's2',
    staff_id: 'b2',
    start_time: '2026-07-21T11:00:00.000Z',
    status: 'pending',
  },
  {
    id: 'bkg3',
    client_id: 'placeholder-tenant-id',
    customer_name: 'James Carter',
    customer_email: 'j.carter@gmail.com',
    customer_phone: '555-456-7890',
    service_id: 's5',
    staff_id: 'b3',
    start_time: '2026-07-22T14:30:00.000Z',
    status: 'completed',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord1',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Robert Stark',
    customer_email: 'robb@winterfell.net',
    customer_phone: '555-222-1111',
    total_amount: 56,
    status: 'completed',
    notes: 'Please leave package near the side door.',
    created_at: '2026-07-19T10:15:30.000Z',
  },
  {
    id: 'ord2',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Gwen Stacy',
    customer_email: 'gwen@midtown.edu',
    customer_phone: '555-888-9999',
    total_amount: 24,
    status: 'pending',
    notes: 'Gift wrapping if possible!',
    created_at: '2026-07-20T08:45:00.000Z',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-101',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Tony Stark',
    customer_email: 'tony@starkindustries.com',
    customer_phone: '555-999-8888',
    amount: 120,
    status: 'paid',
    created_at: '2026-07-15T14:20:00.000Z',
    description: 'Corporate executive grooming session & premium hair care package.',
  },
  {
    id: 'inv-102',
    client_id: 'placeholder-tenant-id',
    customer_name: 'Bruce Wayne',
    customer_email: 'bruce@waynecorp.com',
    customer_phone: '555-777-7777',
    amount: 175,
    status: 'sent',
    created_at: '2026-07-18T10:00:00.000Z',
    description: 'Premium clay styling pack & customized hair and beard alignment.',
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub1',
    client_id: 'placeholder-tenant-id',
    form_name: 'Contact Form',
    customer_name: 'Peter Parker',
    customer_email: 'peter@dailybugle.com',
    message: 'Hey Marcus, do you guys have any openings for a large group cut for a wedding party next month? Let me know!',
    created_at: '2026-07-19T15:30:00.000Z',
  },
  {
    id: 'sub2',
    client_id: 'placeholder-tenant-id',
    form_name: 'Contact Form',
    customer_name: 'Charles Xavier',
    customer_email: 'charles@xavierinstitute.edu',
    message: 'Inquiring about corporate gift cards for our staff members. Thank you.',
    created_at: '2026-07-20T09:12:00.000Z',
  },
];
